### ISSUE TITLE
Travis CI break at head

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/ethereumclassic.github.io#212]
Thanks, @hi_chris.

I have just hit a CI issue which you might be more able to debug than me.   Works fine in development, but hits build error in production:

https://travis-ci.org/ethereumclassic/ethereumclassic.github.io/builds/594379060?utm_source=github_status&utm_medium=notification

For this commit, where I added videos and slides for the first 8 ETC Summit sessions:

https://github.com/ethereumclassic/ethereumclassic.github.io/pull/211

Looks like it is a known issue, and we will need to do some JS workaround for it:

https://github.com/gatsbyjs/gatsby/issues/16287

https://github.com/gatsbyjs/gatsby/issues/309

**Comment by hitchcott** [comment]
It appears that the issue is related to permissions on the `master` branch rather than JS. I assume that this was enabled to prevent malicious updating (now requires 2 people to approve), which makes sense, but broke the Travis CI script.

I have updated the script so that Travis to push to a `staging` branch rather than `master`. A PR can be made from the `staging` branch for approval by moderators. Once the script is complete, you'd need to create a PR from the `staging` branch into master and then it needs to be approved. For example, see https://github.com/ethereumclassic/ethereumclassic.github.io/pull/220, which needs to be approved. 

Seems like this is a better flow as it means nobody can accidentally push a bad update unilaterally, and all updates are documented in PRs.

Other fixes:

- Update CNAME to `ethereumclassic.org`
- Removed some unused files in `source`

**Comment by bobsummerwill** [comment]
Thanks - but the permissions issue was introduced AFTER the initial break, and is just hiding the JS break which will show up again when we get past this first one.

This is the break ...

https://travis-ci.org/ethereumclassic/ethereumclassic.github.io/builds/594379060?utm_source=github_status&utm_medium=notification

Please could you have a look at this, @hitchcott, and see if you can work out what we need to do in the JS to resolve this?

**Comment by bobsummerwill** [comment]
Thanks for the review, @TheEnthusiasticAs.
I have merged now.
Still not convinced that we have addressed the underlying issue, but I guess we will find that out when I try to push my next set of view links through the process.
