### ISSUE TITLE
Link to docs.ethereumclassic.org 

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#261]
I suggest we add a "Documentation" entry in the main menu to:

docs.ethereumclassic.org 

Alternatively, we could add a "Developer Docs" button to the top of the knowledge base.

**Comment by TheEnthusiasticAs** [comment]
I would put the link under Knowledge.  "Knowledge/Documentation" in hamburger bar

**Comment by bobsummerwill** [comment]
@stevanlohja - please could you just merge your content into this site?

To my understanding, you made that site because the main WordPress one was undermaintained and you had no useful means of updating it.   Neither of those is the case anymore.

You only really have two pages:

https://docs.ethereumclassic.org/docs/doc1
https://docs.ethereumclassic.org/blog/2019/10/14/eclc-q3-dev-review

**Comment by hitchcott** [comment]
Happy to add this content if I get a green light.

**Comment by bobsummerwill** [comment]
Sure - adding the link is fine.

And I hope you will seriously considering merging your content, @stevanlohja?

**Comment by gitr0n1n** [comment]
Yes after comparing to Ethereum wiki, EthHub Docs. We definitely need to build this out, especially with an emphasis to utilize our ecoystem's tools like Ethercluster, BUIDL IDE, Jade Suite, Open RPC.

We have great resource to crawl.

**Comment by gitr0n1n** [comment]
Can we redirect https://docs.ethereumclassic.org to https://github.com/ethereumclassic/wiki/wiki

**Comment by gitr0n1n** [comment]
Similar: https://github.com/ethereumclassic/ethereumclassic.github.io/issues/322

**Comment by hitchcott** [comment]
As there's only one article on docs.ethereumclassic.org, I will incorporate some of it's content into the 'what is etc' article, as the beginner's introduction
