### ISSUE TITLE
New Blog Article Contributor

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#276]
From discord:

> If a journalist would like to post his article as blog on etc website, would it be accepted/published?
> it is this article: https://thecurrencyanalytics.com/9355/ethereum-classic-restores-the-ethos-of-original-ethereum-blockchain-like-no-other-sydney-ifergan/

I think this is a great idea. Show of hands?

I assume we'd be ok with `originally posted xxx` with a link to the source?

**Comment by TheEnthusiasticAs** [comment]
completely agree. 
A side note: As he tried to upload the files, he got this message: "Uploads are disabled.
File uploads require push access to this repository."

Do he need to get as a orga member?

**Comment by hitchcott** [comment]
He can fork the repo and submit a PR

**Comment by TheEnthusiasticAs** [comment]
I am fully agree with Bob's comments. Below copied from etc discord:

"I would think it best to say no, a.s. hitchcott.
https://ethereumclassic.org/ is not really the place for opinion pieces.

Perhaps a useful Occam's Razor is to consider what we would do if ETC was already massively successful.   Right up with ETH or BTC on market-cap.   Would we accept a blog post from a journalist?
Ethereum Classic
Ethereum Classic
A decentralized platform that runs smart contracts: applications that run exactly as programmed without downtime, censorship or third party interference

I don't think so.
It's a slippery slope.
The content we want is "landing site" basic information and developer/user onboarding.
Not empty rhetoric.
Not shilling and pumping.
Facts.
If nothing else, we would be giving ourselves more work, because then you end up with a situation whether other journalists (and to be clear, this will really be bloggers and part-time journalists, not professional) are all wanting to push their content in too.
Looking at the blog section, all of the blogs which have gone in there since October (all authored me plus one from Yaz) are actually inappropriate too as well, because they should really be coming from the ETC Coop website - but I wanted to get that blog flow working again and be the guinea pig.

I will migrate those when (imminently) we create a new website for https://etccooperative.org/ using a clone of this repo.   Or whitelabel, as-and-when you get to a state where that is possible, @hitchcott.
ETC Cooperative
sengi
Home
Looking back at the old blog posts, mainly from cseberino, the posts are either educational, or are "weekly newsletter" style.   Both of those are entirely legitimate, I think.   And then right back at the start you have the call to arms, Manifesto, Declaration of Independence, etc.

https://ethereumclassic.org/blog
Ethereum Classic
Blog - Ethereum Classic
Latest Ethereum Classic news articles and announcements

But just random pumping posts are probably a mistake, IMHO.
Happy to hear where others stand on this, though ... ?"
_
End

Also, I left this topic in discord for 1 day open, but there were no more comments to it. So, I am assuming it is agreed by  ETC eco participants, that it is the best way to go with at the moment and I am going to close this issue.

If someone sees it otherwise, pls open it again and comment. Thx
