### ISSUE TITLE
Licensing Questions

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#288]
Currently the site doesn't have a license.

I'm planning licensing my work under a permissive (MIT) license, but I'm not sure how to properly attribute other contributor's works. 

JS libraries etc. seem to be covered by their respective modules, but for things like blog posts and language contributions, do we assume they inherit that MIT license (unless stated otherwise)?

How do we go about this?

**Comment by TheEnthusiasticAs** [comment]
I can't find the issue: There were discussions and the contributors/engineers here licensed their works under Apache 2.0

**Comment by bobsummerwill** [comment]
I would suggest the Mozilla Public License 2 is the best choice for permissive (but patent protected) website projects, @hitchcott.

https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)

It is like the LGPL but with the licensing boundary being source files, not compilation units, which was a C-idiom which made sense in the 1980s but really does not work for websites.

MPL 2.0 basically means that others can incorporate your content into their websites but that they have to share the changes back if they modify your content.   Just like LGPL.   So "using it" requires no permission (just attribution), but if you modify it then you cannot monopolize those changes.

MPL 2.0 is stronger than MIT and BSD because it has patent protection.   People cannot stuff their patented content into your project (without declaring their patents) and then go and troll anybody using project for their patent licenses.

So MPL 2.0 works best for that for web content.
Apache 2.0 does much the same for code.

See https://bobsummerwill.com/2016/07/12/ethereum-everywhere/ and https://en.wikipedia.org/wiki/License_compatibility

**Comment by bobsummerwill** [comment]
It would also be wise for us to introduce a DCO requirement and DCO bot.

https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin

Which is basically a bot which enforces a one-line signoff in each commit where the contributor attests that they created the code and that they have the right to contribute it under the license of the repository.   Gives us an email address attached to the contribution too, so we have a means of contacting contributors.   Note - this is not a "real name" requirement.   Pseudonyms would be OK.

See https://github.com/hyperledger/besu/pull/299/checks for an example of that CI/CD.
