### ISSUE TITLE
Content Page: Learn about Ethereum Classic

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#331]
sitemap: https://ethereumclassic.org/learn

# Learn about Ethereum Classic

Welcome to ethereumclassic.org/learn, a set of resources to help you learn more about Ethereum Classic. This page includes technical and non-technical articles, guides, and resources. If you’re totally new to Ethereum, we suggest you start here.

Here are some excellent starting points:

https://github.com/ethereumclassic/wiki/wiki/Introduction-to-ETC

**Comment by gitr0n1n** [comment]
https://ethereum.gitbooks.io/frontier-guide/content/index.html

**Comment by gitr0n1n** [comment]
@TheEnthusiasticAs we need some good beginer guides to on-board people to ETC.

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n 
If you mean for a non-tech guy, then the "Declaration of Independence" would be the good one. It gives the info, why it was born:
https://ethereumclassic.org/blog/2016-08-13-declaration-of-independence

Also, on this page Chris gathered good contents: https://ethereumclassic.org/knowledge. I would copy-paste the etherplan's contents and refer to etherplan's homepage and his author. Because one that page could go offline and the content is very good.
