### ISSUE TITLE
Merge Browser Wallets 

### ISSUE THREAD

**Issue by hitchcott** [ethereumclassic/ethereumclassic.github.io#363]

**Comment by gitr0n1n** [comment]
Browser Wallets:
Remove detailed description and aggregate to one list instead of 3.

Hard Wallet:
Add: [Ellipal](https://www.ellipal.com/)


Software Wallets:
Remove: BC Vault, BitBox02 Multi Edition, CoolWallet, Ellipal


Other Wallet Products:
Add: Category description: "These products are complimentary to crypto wallets (e.g.: recovery seed storage)."
Remove: Product Desciriptions and turn these into buttons like the wallets. No need to give these products so much real estate.
