### ISSUE TITLE
Editing index.html does not change the website

### ISSUE THREAD

**Issue by arvicco** [ethereumclassic/ethereumclassic.github.io#40]
@dax-classix It doesn't look like any changes to index.html on master branch propagate to website. Could you please explain how we can edit the content of the website now?

**Comment by dax-classix** [comment]
Hi @arvicco , the site uses the [gatsby](https://github.com/gatsbyjs/gatsby) static site generator.

The source code and readme is on the `dax-redesign` branch (readme refers to `gh-pages` instead of `master` as the destination branch atm, though).

I will find time this weekend to clean up this and create an automated build process with something like:

* Develop (gatsby source files, pushes do not trigger releases)
* Release (any changes get pushed here will auto-rebuild to and pushed to master)
* Master (generated html, automatically pushed to)

**Comment by NDNewell** [comment]
@dax-classix your readme isn't clear for me. What process should I follow to create proper pull requests?

**Comment by dax-classix** [comment]
@NDNewell to create a new PR, you would fork, checkout `source` and submit the PR back into `source` -- similar to the recent PR https://github.com/ethereumclassic/ethereumclassic.github.io/pull/46

After the merge happens, travis automatically rebuilds the HTML and the frontend is updated.

**Comment by NDNewell** [comment]
@dax-classix thanks for the clarification. Will make note.
